apiVersion: harness.io/v1
kind: api
type: openapi
identifier: springbootdemoapi_v2  # 👈 CHANGED THIS VALUE
name: my-java-api
owner: user:account/your_harness_email@domain.com
orgIdentifier: playground
projectIdentifier: mak_playground
spec:
  lifecycle: experimental
  definition:
    $text: ./api-definition.yaml
metadata:
  description: OpenAPI 3.0 contract definition for item manipulation.
