apiVersion: harness.io/v1
kind: api
identifier: springbootdemoapi
name: Spring Boot Demo API
type: openapi
owner: demo-team
orgIdentifier: playground
projectIdentifier: mak_playground
spec:
  lifecycle: experimental
  definition:
    $text: ./api-definition.yaml # This links the two files together
metadata:
  description: OpenAPI 3.0 contract definition for item manipulation.
