apiVersion: harness.io/v1
kind: Component
type: service
identifier: myjavaapp
name: my-java-app
owner: group:account/devops_developer_user_group
orgIdentifier: playground
projectIdentifier: mak_playground
spec:
  lifecycle: experimental
  sourceCode:
    provider: github
    repoName: my-java-app
    connectorRef: MyGitHubConnector
    branch: test-branch
    monoRepo: false
    url: https://github.com/mastermak-avyka/my-java-app/tree/test-branch
  system:
  - system:account.playground.mak_playground/Java_App
metadata:
  description: Test catalog entry for my-java-app
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/mastermak-avyka/my-java-app/tree/test-branch
  tags:
  - java
  - harness-idp
  - idp
  - api
