apiVersion: harness.io/v1
kind: Component
type: service
identifier: myjavaapp
name: my-java-app
owner: group:account/_account_all_users
orgIdentifier: playground
projectIdentifier: mak_playground
spec:
  lifecycle: dev
  sourceCode:
    provider: Github
    repoName: my-java-app
    connectorRef: MyGitHubConnector
    branch: test-branch
    monoRepo: false
    url: https://github.com/mastermak-avyka/my-java-app/tree/test-branch
metadata:
  tags:
  - idp
  - java
